### ISSUE TITLE
Error on loading

### ISSUE THREAD

**Issue by imagelesskink** [grim3212/AssortedCore#2]
When starting up minecraft, it says there was an error in loading. Log file attached.
[2021-08-18-4.log](https://github.com/grim3212/AssortedCore/files/7011123/2021-08-18-4.log)

**Comment by grim3212** [comment]
It looks like it broke as a result of the latest Forge changes to harvestability. 

I will get a new version out that fixes this.

**Comment by grim3212** [comment]
Should be fixed when 2.0.1 is available
