### ISSUE TITLE
https://assortedmods.com/core does not have a valid SSL certificate

### ISSUE THREAD

**Issue by TheDraconicAge** [grim3212/AssortedCore#3]
I am attempting to check the documentation link and finding a Cloudflare error screen. On the most recent reload:
Ray ID: 6814367b68e8b677 • 2021-08-19 14:53:41 UTC

**Comment by grim3212** [comment]
Thanks for the notification. Should be resolved! Not sure what happened to the server it's running on but looks like it is back up.
